CREATE OR ALTER VIEW Employee_vw AS
SELECT
	EMPLOYEE_ID AS Employee_ID,
	CAST(FULL_NAME AS VARCHAR(150)) AS Full_Name,
	CAST(GENDER AS VARCHAR(20)) AS Gender,
	CAST(BIRTH_DATE AS DATE) AS Birth_Date,
	CAST(EMPLOYMENT_DATE AS DATE) AS Employment_Date,
	CAST(CATEGORY AS VARCHAR(50)) AS Category,
	EDUCATION_LEVEL AS Education_Level
FROM employee_stg;